# File: roles/docker/tasks/main.yml

- name: Ensure /etc/apt/keyrings exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker Repository (DEB822 format)
  ansible.builtin.deb822_repository:
    name: docker
    types: [deb]
    uris: ["https://download.docker.com/linux/debian"]
    # For Debian 13 we use bookworm since trixie is not officially supported yet
    suites: ["trixie"]
    components: [stable]
    signed_by: /etc/apt/keyrings/docker.asc
    state: present

- name: Install Docker Packages
  ansible.builtin.apt:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
      - fuse-overlayfs
      - uidmap  
    # state: latest
    state: present
    update_cache: true
    # update_cache: false
    # allow_downgrade: false


- name: Configure Docker Storage Driver for LXC
  ansible.builtin.copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "storage-driver": "fuse-overlayfs", 
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "10m",
          "max-file": "3"
        }
      }
  register: docker_cfg # Register change for immediate restart

# NOTE: Restart Docker immediately, not waiting for end of playbook
- name: Restart Docker immediately
  ansible.builtin.systemd_service:
    name: docker
    state: restarted
  when: docker_cfg.changed